//
//  TopPostWorker.swift
//  Coding-Task
//
//  Created by Jonathan on 2/26/18.
//  Copyright (c) 2018 Jonathan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TopPostWorker {
    let client = Client()
    func getTopPost(after: String, completion: @escaping (_ json: Data) -> Void) {
        client.fetch(after: after) { json in
            completion(json)
        }
    }
}
