//
//  TopPostModels.swift
//  Coding-Task
//
//  Created by Jonathan on 2/26/18.
//  Copyright (c) 2018 Jonathan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TopPost {

    // MARK: Use cases

    enum Listing {
        struct Request {
            var after: String!
        }

        struct Response {
            var data: Data!
        }

        struct Listings: Codable {
            var data: ListingData!
        }

        struct ListingData: Codable {
            var children: [SubReddit] = []
            var after: String!
        }

        struct SubReddit: Codable {
            var data: SubRedditData!
        }

        struct SubRedditData: Codable {
            var title: String!
            var author: String!
            var created: Int!
            var thumbnail: String!
            var num_comments: Int!
            var preview: Preview!
        }

        class Preview: Codable {
            var images: [PreviewImage]?
        }

        class PreviewImage: Codable {
            var source: ImageSource!
        }

        class ImageSource: Codable {
            var url: String!
        }

        struct ListingModel {
            var title: String!
            var author: String!
            var created: Int!
            var thumbnail: String!
            var num_comments: Int!
            var preview: String!
            var after: String!
        }
    }
}
