//
//  TopPostPresenter.swift
//  Coding-Task
//
//  Created by Jonathan on 2/26/18.
//  Copyright (c) 2018 Jonathan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopPostPresentationLogic {
    func presentTopPost(response: TopPost.Listing.Response)
}

class TopPostPresenter: TopPostPresentationLogic {
    weak var viewController: TopPostDisplayLogic?

    // MARK: Do something

    func presentTopPost(response: TopPost.Listing.Response) {
        var listings:TopPost.Listing.Listings!
        let decoder = JSONDecoder()
        var listingArray:[TopPost.Listing.ListingModel] = []
        
        do {
            listings = try decoder.decode(TopPost.Listing.Listings.self, from: response.data)
            
        }catch {
            
        }
        
        for object in listings.data.children {
            var listing = TopPost.Listing.ListingModel()
            listing.after = listings.data.after
            listing.author = object.data.author
            listing.created = object.data.created
            listing.thumbnail = object.data.thumbnail
            listing.title = object.data.title
            listing.num_comments = object.data.num_comments
            if let preview = object.data.preview {
            
                if let images = preview.images {
                    if let currentImage:TopPost.Listing.PreviewImage? = images[0] {
                        if let sourceImage = currentImage?.source {
                            listing.preview = sourceImage.url ?? ""
                        }
                    }
                }
            }
            listingArray.append(listing)
        }
        
        
        viewController?.displayTopPost(viewModel: listingArray)
    }
}
