//
//  TopPostInteractor.swift
//  Coding-Task
//
//  Created by Jonathan on 2/26/18.
//  Copyright (c) 2018 Jonathan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopPostBusinessLogic {
    func getTopPost(request: TopPost.Listing.Request)
}

protocol TopPostDataStore {
    // var name: String { get set }
}

class TopPostInteractor: TopPostBusinessLogic, TopPostDataStore {
    var presenter: TopPostPresentationLogic?
    var worker: TopPostWorker?
    // var name: String = ""

    // MARK: Do something

    func getTopPost(request: TopPost.Listing.Request) {
        worker = TopPostWorker()
        worker?.getTopPost(after:request.after,completion: { (data) in
            
            var response = TopPost.Listing.Response()
            response.data = data
            self.presenter?.presentTopPost(response: response)
        })

        
    }
}
